// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXao1AZ_8j35P5L4cfDhPnT4ruFe3sF4c',
    appId: '1:808637869294:web:72ac73434a5f0e1bf2d7ff',
    messagingSenderId: '808637869294',
    projectId: 'smart-fire-system-app',
    authDomain: 'smart-fire-system-app.firebaseapp.com',
    storageBucket: 'smart-fire-system-app.appspot.com',
    measurementId: 'G-763V0FMT0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVz7njpgc4ILHI5OkXdNPiYvPqK_hYglc',
    appId: '1:808637869294:android:17b5073374ede5c7f2d7ff',
    messagingSenderId: '808637869294',
    projectId: 'smart-fire-system-app',
    storageBucket: 'smart-fire-system-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs3pb1xxu4aBx4eNvjfpxhQSdZMh25WP4',
    appId: '1:808637869294:ios:46af606037181c7ef2d7ff',
    messagingSenderId: '808637869294',
    projectId: 'smart-fire-system-app',
    storageBucket: 'smart-fire-system-app.appspot.com',
    iosClientId: '808637869294-fb328bha1l8ntl2uld7obq97itbq0lff.apps.googleusercontent.com',
    iosBundleId: 'com.erdwaz.fireAlarmSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs3pb1xxu4aBx4eNvjfpxhQSdZMh25WP4',
    appId: '1:808637869294:ios:46af606037181c7ef2d7ff',
    messagingSenderId: '808637869294',
    projectId: 'smart-fire-system-app',
    storageBucket: 'smart-fire-system-app.appspot.com',
    iosClientId: '808637869294-fb328bha1l8ntl2uld7obq97itbq0lff.apps.googleusercontent.com',
    iosBundleId: 'com.erdwaz.fireAlarmSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXao1AZ_8j35P5L4cfDhPnT4ruFe3sF4c',
    appId: '1:808637869294:web:11bca8ef47154787f2d7ff',
    messagingSenderId: '808637869294',
    projectId: 'smart-fire-system-app',
    authDomain: 'smart-fire-system-app.firebaseapp.com',
    storageBucket: 'smart-fire-system-app.appspot.com',
    measurementId: 'G-QQHWKHTCD7',
  );
}
